config/routes.rb
Rails.application.routes.draw do

root :to => 'public/homes#top'
get 'about' => 'public/homes#about'
get 'items' => 'public/items#index'
get 'items/:id' => 'public/items#show', as: 'item'
get 'customers/my_page' => 'public/customers#show'
get 'customers/information/edit' => 'public/customers#edit'
patch 'customers/information' => 'public/customers#update'
get 'customers/unsubscribe' => 'public/customers#unsubscribe'
patch 'customers/withdraw' => 'public/customers#withdraw'
get 'cart_items' => 'public/cart_items#index'
patch 'cart_items/:id' => 'public/cart_items#update'
delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
delete 'cart_items/:id' => 'public/cart_items#destroy'
post 'cart_items' => 'public/cart_items#create'
get 'orders/new' => 'public/orders#new'
post 'orders/confirm' => 'public/orders#confirm'
get 'orders/complete' => 'public/orders#complete'
post 'orders' => 'public/orders#create'
get 'orders' => 'public/orders#index'
get 'orders/:id' => 'public/orders#show'
get 'addresses' => 'public/addresses#index'
post 'addresses' => 'public/addresses#create'
get 'addresses/:id/edit' => 'public/addresses#edit', as: 'edit_addresses'
patch 'addresses/:id' => 'public/addresses#update'
delete 'addresses/:id' => 'public/addresses#destroy', as: 'destroy_addresses'
get 'admin' => 'admin/homes#top'
patch 'admin/orders/:order_id/order_details/:id' => 'admin/order_details#update'

# 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end

# 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def add_tax_price
    (self.price * 1.1).round
  end

  validates :genre_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :image, presence: true
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
#管理者側
  def new
    @newitem = Item.new
  end

  def create
    @newitem = Item.new(item_params)
    if @newitem.save
      redirect_to admin_item_path(@newitem.id)
    else
      @items = Item.page(params[:page])
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.page(params[:page])
  end

  def edit
    @edititem = Item.find(params[:id])
  end

  def update
    @edititem = Item.find(params[:id])
    if @edititem.update(item_params)
      redirect_to admin_item_path
    else
      #本当はrenderでエラーメッセージも表示させたいが…
      redirect_to admin_item_path
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end


end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<!--（管理者）商品編集-->
<main>
  <div class = "container" style = "margin-top: 40px">
    <div class = "row">
      <div class = "offset-1 h3">
        <div style = "background-color: #EEEEEE; text-align: center; padding: 0 20px">商品編集</div>
      </div>
    </div>
    <%= form_with model: @edititem, :url => {:action => :update}, method: :patch do |f| %>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-2 d-flex align-items-center">
          <%= f.label :商品画像, :style => "margin: 0" %>
        </div>
        <div class = "col-4">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-2 d-flex align-items-center">
          <%= f.label :商品名, :style => "margin: 0" %>
        </div>
        <div class = "col-4">
          <%= f.text_field :name, placeholder: "商品名", class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px;">
        <div class = "col-2 offset-2">
          <%= f.label :商品説明, :style => "margin-top: 8px" %>
        </div>
        <div class = "col-4">
          <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: "form-control", :style => "height: 150px" %>
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-2 d-flex align-items-center">
          <%= f.label :ジャンル, :style => "margin: 0" %>
        </div>
        <div class = "col-4">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "--選択してください--"}, class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-2 d-flex align-items-center">
          <%= f.label :税抜価格, :style => "margin: 0" %>
        </div>
        <div class = "col-4">
          <%= f.text_field :price , placeholder: "1000", class: "form-control" %>
        </div>
        <div class = "col-1 d-flex align-items-center" style = "padding: 0">
          円
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-2">
          <%= f.label :販売ステータス %>
        </div>
        <div class = "col-4">
          <%= f.radio_button :is_active, true %>
          <%= f.label :is_active, "販売中", value: true %>
          <%= f.radio_button :is_active, false, :style => "margin-left:20px;" %>
          <%= f.label :is_active, "販売停止中", value: false %>
        </div>
      </div>
      <div  class = "row form-group">
        <div class = "col-2 offset-5">
          <%= f.submit '変更を保存', class: "form-control btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/admin/items/index.html.erb
<!--（管理者）商品一覧-->
<main>
  <div class = "container-fluid" style = "margin-top: 40px">
    <div class = "row">
      <div class = "offset-1 h3">
        <div style = "background-color: #EEEEEE; text-align: center; padding: 0 20px">商品一覧</div>
      </div>
      <div class = "offset-8">
        <%= link_to "＋", new_admin_item_path, class: "btn btn-light rounded-circle p-0 ", :style => "width: 2rem; height: 2rem" %>
      </div>
    </div>
  <div class = "row" style = "margin-top: 20px">
    <div class = "col-10 offset-1">
      <table class= "table table-borderless border-top border-bottom">
        <thead>
          <tr bgcolor = "#EEEEEE">
            <th class = "col-1">商品ID</th>
            <th class = "col-2">商品名</th>
            <th class = "col-1">税抜価格</th>
            <th class = "col-2">ジャンル</th>
            <th class = "col-1">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td><!--色は消すべき？-->
              <td>
                <%= link_to admin_item_path(item.id) do %>
                  <u style = "color:black"><%= item.name %></u>
                <% end %>
              </td>
              <td><%= item.price.to_s(:delimited) %></td>
              <td><%= item.genre.name %></td>
              <% if item.is_active == true %>
                <td class = "text-success"><b>販売中</b></td>
              <% else %>
                <td class = "text-secondary"><b>販売停止中</b></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class = "d-flex align-items-center justify-content-center"
      <%= paginate @items, theme: 'bootstrap-5' %>
    </div>
  </div>
</main>

app/views/admin/items/new.html.erb
<!--（管理者）商品新規登録-->
<main>
  <div class = "container" style = "margin-top: 40px">
    <div class = "row">
      <div class = "h3">
        <div style = "background-color: #EEEEEE; text-align: center; padding: 0 20px">商品新規登録</div>
      </div>
    </div>
    <%= form_with model: @newitem, :url => {:action => :create}, method: :post do |f| %>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-1 d-flex align-items-center">
          <%= f.label :商品画像, :style => "margin: 0" %>
        </div>
        <div class = "col-4">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-1 d-flex align-items-center">
          <%= f.label :商品名, :style => "margin: 0" %>
        </div>
        <div class = "col-4">
        <%= f.text_field :name, placeholder: "商品名", class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-1">
          <%= f.label :商品説明, :style => "margin-top: 8px" %>
        </div>
        <div class = "col-4">
          <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: "form-control", :style => "height: 150px" %>
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-1 d-flex align-items-center">
          <%= f.label :ジャンル, :style => "margin: 0" %>
        </div>
        <div class = "col-4">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "--選択してください--" }, class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-1 d-flex align-items-center">
          <%= f.label :税抜価格, :style => "margin: 0" %>
        </div>
        <div class = "col-4">
          <%= f.text_field :price , placeholder: "1000", class: "form-control" %>
        </div>
        <div class = "col-1 d-flex align-items-center" style = "padding: 0">
          円
        </div>
      </div>
      <div class = "row form-group" style = "margin-top: 20px">
        <div class = "col-2 offset-1 d-flex align-items-center">
          <%= f.label :販売ステータス, :style => "margin: 0" %>
        </div>
        <div class = "col-4">
          <%= f.radio_button :is_active, true %>
          <%= f.label :is_active, "販売中", value: true %>
          <%= f.radio_button :is_active, false, :style => "margin-left:20px;" %>
          <%= f.label :is_active, "販売停止中", value: false %>
        </div>
      </div>
      <div  class = "row form-group" style = "margin-top: 30px">
        <div class = "col-2 offset-4">
          <%= f.submit '新規登録', class: "form-control btn btn-success" %>
        </div>
    <% end %>
  </div>
</main>

app/views/admin/items/show.html.erb
<!--（管理者）商品詳細-->
<main>
  <div class = "container-fluid" style = "margin-top: 40px">
    <div class = "row">
      <div class = "offset-1 h3">
        <div style = "background-color: #EEEEEE; text-align: center; padding: 0 20px">商品詳細</div>
      </div>
    </div>
    <div class = "row">
      <div class = "col-3 offset-1">
        <!--画像のサイズ指定が必要-->
        <%= image_tag @item.image, class: "img-fluid" %>
      </div>
      <div class ="col-8">
        <div class = "row">
          <div class = "col-2">商品名</div>
          <div class = "col-10"><%= @item.name %></div>
        </div>
        <div class = "row" style = "margin-top:20px">
          <div class = "col-2">商品説明</div>
          <div class = "col-10"><%= @item.introduction %></div>
        </div>
        <div class = "row" style = "margin-top:20px">
          <div class = "col-2">ジャンル</div>
          <div class = "col-10"><%= @item.genre.name %></div>
        </div>
        <div class = "row" style = "margin-top:20px">
          <div class = "col-2">税込価格<br>(税抜価格)</div>
          <div class = "col-10"><%= @item.add_tax_price.to_s(:delimited) %>（<%= @item.price.to_s(:delimited) %>）円</div>
        </div>
        <div class = "row" style = "margin-top:20px">
          <div class = "col-2">販売ステータス</div>
          <div class = "col-10">
            <% if @item.is_active == true %><p class = "text-success"><b>販売中</b></p>
            <% else %><p class = "text-secondary">販売停止中</p>
            <% end %>
          </div>
        </div>
        <div class = "row" style = "margin-top:30px">
          <div class = "col-2 offset-1">
            <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>