config/routes.rb
Rails.application.routes.draw do

root :to => 'public/homes#top'
get 'about' => 'public/homes#about'
get 'items' => 'public/items#index'
get 'items/:id' => 'public/items#show', as: 'item'
get 'customers/my_page' => 'public/customers#show'
get 'customers/information/edit' => 'public/customers#edit'
patch 'customers/information' => 'public/customers#update'
get 'customers/unsubscribe' => 'public/customers#unsubscribe'
patch 'customers/withdraw' => 'public/customers#withdraw'
get 'cart_items' => 'public/cart_items#index'
patch 'cart_items/:id' => 'public/cart_items#update'
delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
delete 'cart_items/:id' => 'public/cart_items#destroy'
post 'cart_items' => 'public/cart_items#create'
get 'orders/new' => 'public/orders#new'
post 'orders/confirm' => 'public/orders#confirm'
get 'orders/complete' => 'public/orders#complete'
post 'orders' => 'public/orders#create'
get 'orders' => 'public/orders#index'
get 'orders/:id' => 'public/orders#show'
get 'addresses' => 'public/addresses#index'
post 'addresses' => 'public/addresses#create'
get 'addresses/:id/edit' => 'public/addresses#edit', as: 'edit_addresses'
patch 'addresses/:id' => 'public/addresses#update'
delete 'addresses/:id' => 'public/addresses#destroy', as: 'destroy_addresses'
get 'admin' => 'admin/homes#top'
patch 'admin/orders/:order_id/order_details/:id' => 'admin/order_details#update'

# 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end

# 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @editcustomer = Customer.find(params[:id])
  end

  def update
    @editcustomer = Customer.find(params[:id])
    if @editcustomer.update(customer_params)
      redirect_to admin_customer_path
    else
      #本当はrenderでエラーメッセージを表示させたいがエラーになる
      redirect_to admin_customer_path
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<!--（管理者）会員情報編集-->
<main>
  <div class = "container-fluid" style = "margin-top: 40px">
    <div class = "row">
      <div class = "offset-1 h3">
        <div style = "background-color: #EEEEEE; text-align: center; padding: 0 20px">
          <%= @editcustomer.last_name %><%= @editcustomer.first_name %>さんの会員情報編集
        </div>
      </div>
    </div>
    <div class = "row" style = "margin-top: 20px; margin-bottom: 16px">
      <div class = "col-1 offset-1">
        会員ID
      </div>
      <div class = "col-1">
        <%= @editcustomer.id %>
      </div>
    </div>
    <%= form_with model: @editcustomer, url: admin_customer_path(id = @editcustomer.id), method: :patch do |f| %>
      <div class = "row form-group">
        <div class = "col-1 offset-1">
          氏名
        </div>
        <div class = "col-2">
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
        <div class = "col-2">
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group">
        <div class = "col-1 offset-1">
          フリガナ
        </div>
        <div class = "col-2">
          <%= f.text_field :last_name_kana, class: "form-control" %>
        </div>
        <div class = "col-2">
          <%= f.text_field :first_name_kana, class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group">
        <div class = "col-1 offset-1">
          郵便番号
        </div>
        <div class = "col-2">
          <%= f.text_field :postal_code, class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group">
        <div class = "col-1 offset-1">
          住所
        </div>
        <div class = "col-5">
          <%= f.text_field :address, class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group">
        <div class = "col-1 offset-1">
          電話番号
        </div>
        <div class = "col-2">
          <%= f.text_field :telephone_number, class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group">
        <div class = "col-1 offset-1">
          メールアドレス
        </div>
        <div class = "col-2">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
      <div class = "row form-group">
        <div class = "col-1 offset-1">
          会員ステータス
        </div>
        <div class = "col-2">
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted, "有効", {value: :false} %>
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted, "退会", {value: :true} %>
        </div>
      </div>
      <div class = "row">
        <div class = "col-2 offset-2">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/admin/customers/index.html.erb
<!--（管理者）会員一覧-->
<main>
  <div class = "container-fluid" style = "margin-top: 40px">
    <div class = "row">
      <div class = "offset-1 h3">
        <div style = "background-color: #EEEEEE; text-align: center; padding: 0 20px">会員一覧</div>
      </div>
    </div>
  <div class = "row" style = "margin-top: 20px">
    <div class = "col-10 offset-1">
      <table class = "table">
        <thead>
          <tr bgcolor = "#EEEEEE">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer.id) do %>
                  <u class = "text-dark"><%= customer.last_name %><%= customer.first_name %></u>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <% if customer.is_deleted == true %>
                <td style = "color: gray">退会</td>
              <% else %>
                <td class = "text-success">有効</td>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class = "d-flex align-items-center justify-content-center">
        <%= paginate @customers, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</main>

app/views/admin/customers/show.html.erb
<!--（管理者）会員詳細-->
<main>
  <div class = "container-fluid" style = "margin-top: 40px">
    <div class = "row">
      <div class = "offset-1 h3">
        <div style = "background-color: #EEEEEE; text-align: center; padding: 0 20px">
          <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
        </div>
      </div>
    </div>
    <div class = "row" style = "margin-top: 20px">
      <div class = "col-1 offset-1">
        会員ID
      </div>
      <div>
        <%= @customer.id %>
      </div>
    </div>
    <div class = "row" style = "margin-top: 20px">
      <div class = "col-1 offset-1">
        氏名
      </div>
      <div>
        <%= @customer.last_name %>　<%= @customer.first_name %>
      </div>
    </div>
    <div class = "row" style = "margin-top: 20px">
      <div class = "col-1 offset-1">
        フリガナ
      </div>
      <div>
        <%= @customer.last_name_kana %>　<%= @customer.first_name_kana %>
      </div>
    </div>

    <div class = "row" style = "margin-top: 20px">
      <div class = "col-1 offset-1">
        郵便番号
      </div>
      <div>
        <%= @customer.postal_code %>
      </div>
    </div>

    <div class = "row" style = "margin-top: 20px">
      <div class = "col-1 offset-1">
        住所
      </div>
      <div>
        <%= @customer.address %>
      </div>
    </div>

    <div class = "row" style = "margin-top: 20px">
      <div class = "col-1 offset-1">
        電話番号
      </div>
      <div>
        <%= @customer.telephone_number %>
      </div>
    </div>

    <div class = "row" style = "margin-top: 20px">
      <div class = "col-1 offset-1">
        メールアドレス
      </div>
      <div>
        <%= @customer.email %>
      </div>
    </div>

    <div class = "row" style = "margin-top: 20px">
      <div class = "col-1 offset-1">
        会員ステータス
      </div>
      <% if @customer.is_deleted == true %>
        <div>
          退会
        </div>
      <% else %>
        <div class = "text-success">
          有効
        </div>
      <% end %>
    </div>

    <div class = "row" style = "margin-top: 20px">
      <div class = "col-1 offset-2" style = "padding-left: 0">
        <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
      </div>
      <div class = "col-2">
        <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</main>