config/routes.rb
Rails.application.routes.draw do

root :to => 'public/homes#top'
get 'about' => 'public/homes#about'
get 'items' => 'public/items#index'
get 'items/:id' => 'public/items#show', as: 'item'
get 'customers/my_page' => 'public/customers#show'
get 'customers/information/edit' => 'public/customers#edit'
patch 'customers/information' => 'public/customers#update'
get 'customers/unsubscribe' => 'public/customers#unsubscribe'
patch 'customers/withdraw' => 'public/customers#withdraw'
get 'cart_items' => 'public/cart_items#index'
patch 'cart_items/:id' => 'public/cart_items#update'
delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
delete 'cart_items/:id' => 'public/cart_items#destroy'
post 'cart_items' => 'public/cart_items#create'
get 'orders/new' => 'public/orders#new'
post 'orders/confirm' => 'public/orders#confirm'
get 'orders/complete' => 'public/orders#complete'
post 'orders' => 'public/orders#create'
get 'orders' => 'public/orders#index'
get 'orders/:id' => 'public/orders#show'
get 'addresses' => 'public/addresses#index'
post 'addresses' => 'public/addresses#create'
get 'addresses/:id/edit' => 'public/addresses#edit', as: 'edit_addresses'
patch 'addresses/:id' => 'public/addresses#update'
delete 'addresses/:id' => 'public/addresses#destroy', as: 'destroy_addresses'
get 'admin' => 'admin/homes#top'
patch 'admin/orders/:order_id/order_details/:id' => 'admin/order_details#update'

# 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end

# 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production:2, shipping_preparation:3, shipped:4 }

  validates :customer_id, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_price, presence: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    if order.update(order_params)
      redirect_to admin_order_path(order.id)
    else
      render :show
    end
  end

  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<!--（管理者）注文履歴詳細-->
<main>
  <div class = "container-fluid" style = "margin-top: 40px">
    <div class = "row">
      <div class = "offset-1 h3">
        <div style = "background-color: #EEEEEE; text-align: center; padding: 0 20px">注文履歴一覧</div>
      </div>
    </div>
    <div class = "row">
      <table class = "table table-borderless offset-1">
        <tr>
          <th class = "col-1">購入者</th>
          <td class = "col-2">
            <%= link_to admin_customer_path(id = @order.customer.id) do %>
              <u class = "text-dark"><%= @order.customer.last_name %> <%= @order.customer.first_name %></u>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class = "col-1">注文日</th>
          <td class = "col-2"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th class = "col-1">配送先</th>
          <td colspan = "5">〒<%= @order.shipping_postal_code %> <%= @order.shipping_address %><br><%= @order.shipping_name %></td>
        </tr>
        <tr>
          <th class = "col-1">支払方法</th>
          <td class = "col-2"><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th class = "col-1">注文ステータス</th>
          <%= form_with model: @order, url: admin_order_path(id = @order.id), method: :patch do |f| %>
            <td colspan = "1">
              <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]}, {}, {class: "form-control"} %>
            </td>
            <td>
              <%= f.submit '更新', class: "btn btn-success" %>
            </td>
          <% end %>
          <td class = "col-10"></td>
        </tr>
      </table>
    </div>
    <div class = "row">
      <div class = "col-8 offset-1">
        <table class = "table table-borderless border-top border-bottom">
          <thead>
            <tr bgcolor = "#EEEEEE">
              <th class = "col-3">商品名</th>
              <th class = "col-1">単価(税込)</th>
              <th class = "col-1">数量</th>
              <th class = "col-1">小計</th>
              <th colspan = "2">製作ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_details.each do |order_detail| %>
              <tr>
                <td class = "col-3"><%= order_detail.item.name %></td>
                <td class = "col-1"><%= order_detail.purchase_price.to_s(:delimited) %></td>
                <td class = "col-1"><%= order_detail.amount %></td>
                <td class = "col-1"><%= (order_detail.purchase_price * order_detail.amount).to_s(:delimited) %></td>
                <!--【エラー】admin/orders/admin/:order_id/order_details/:id　と"orders/"の後ろに何故かもう一度"admin"が出てエラーになっているみたい-->
                <%= form_with model: order_detail, url: "#{order_detail.order_id}/order_details/#{order_detail.id}", method: :patch do |f| %>
                  <td class = "col-1">
                    <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]}, {}, {class: "form-control"} %>
                  </td>
                  <td class = "col-1">
                    <%= f.submit '更新', class: "btn btn-success" %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class = "col-2 d-flex align-items-end" style = "margin-left: 40px">
        <table class = "table table-borderless">
          <tr>
            <th scope = "col" style = "width:25%">商品合計</th>
            <td scope = "col" class = "text-right" style = "width:20%"><%= (@order.total_price - @order.shipping_price).to_s(:delimited) %>円</td>
            <td scope = "col" style = "width:10%"></td>
          </tr>
          <tr>
            <th>送料</th>
            <td class = "text-right"><%= @order.shipping_price.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td class = "text-right"><%= @order.total_price.to_s(:delimited) %>円</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</main>