config/routes.rb
Rails.application.routes.draw do

root :to => 'public/homes#top'
get 'about' => 'public/homes#about'
get 'items' => 'public/items#index'
get 'items/:id' => 'public/items#show', as: 'item'
get 'customers/my_page' => 'public/customers#show'
get 'customers/information/edit' => 'public/customers#edit'
patch 'customers/information' => 'public/customers#update'
get 'customers/unsubscribe' => 'public/customers#unsubscribe'
patch 'customers/withdraw' => 'public/customers#withdraw'
get 'cart_items' => 'public/cart_items#index'
patch 'cart_items/:id' => 'public/cart_items#update'
delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
delete 'cart_items/:id' => 'public/cart_items#destroy'
post 'cart_items' => 'public/cart_items#create'
get 'orders/new' => 'public/orders#new'
post 'orders/confirm' => 'public/orders#confirm'
get 'orders/complete' => 'public/orders#complete'
post 'orders' => 'public/orders#create'
get 'orders' => 'public/orders#index'
get 'orders/:id' => 'public/orders#show'
get 'addresses' => 'public/addresses#index'
post 'addresses' => 'public/addresses#create'
get 'addresses/:id/edit' => 'public/addresses#edit', as: 'edit_addresses'
patch 'addresses/:id' => 'public/addresses#update'
delete 'addresses/:id' => 'public/addresses#destroy', as: 'destroy_addresses'
get 'admin' => 'admin/homes#top'
patch 'admin/orders/:order_id/order_details/:id' => 'admin/order_details#update'

# 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end

# 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :customer_id, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def subtotal
    item.add_tax_price * amount
  end

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def add_tax_price
    (self.price * 1.1).round
  end

  validates :genre_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :image, presence: true
  
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production:2, shipping_preparation:3, shipped:4 }

  validates :customer_id, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_price, presence: true

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  enum making_status: { cannot_produce: 0, waiting_for_production: 1, in_production:2, production_completed:3 }

  validates :item_id, presence: true
  validates :order_id, presence: true
  validates :purchase_price, presence: true
  validates :amount, presence: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @newgenre = Genre.new
  end

  def create
    @newgenre = Genre.new(genre_params)
    @newgenre.save
    redirect_to '/admin/genres'
  end

  def edit
    @editgenre = Genre.find(params[:id])
  end

  def update
    @editgenre = Genre.find(params[:id])
    if @editgenre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
#管理者側
  def new
    @newitem = Item.new
  end

  def create
    @newitem = Item.new(item_params)
    if @newitem.save
      redirect_to admin_item_path(@newitem.id)
    else
      @items = Item.page(params[:page])
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.page(params[:page])
  end

  def edit
    @edititem = Item.find(params[:id])
  end

  def update
    @edititem = Item.find(params[:id])
    if @edititem.update(item_params)
      redirect_to admin_item_path
    else
      #本当はrenderでエラーメッセージも表示させたいが…
      redirect_to admin_item_path
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    if order.update(order_params)
      redirect_to admin_order_path(order.id)
    else
      render :show
    end
  end

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_path
      else
        root_path
      end
    end

    def
      after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :customer
        root_path
      elsif resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
      #devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧", "/admin/items" , class: "btn btn-light text-nowrap", :style => "width:120px" %>
              </li><span>　</span>
              <li class="nav-item">
                <%= link_to "会員一覧", "/admin/customers" , class: "btn btn-light text-nowrap", :style => "width:120px" %>
              </li><span>　</span>
              <li class="nav-item">
                <%= link_to "注文履歴一覧", admin_path, class: "btn btn-light text-nowrap", :style => "width:120px" %>
              </li><span>　</span>
              <li class="nav-item">
                <%= link_to "ジャンル一覧", "/admin/genres" , class: "btn btn-light text-nowrap", :style => "width:120px" %>
              </li><span>　</span>

              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-light text-nowrap" %>
              </li>

            <% elsif customer_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", customers_my_page_path, class: "btn btn-light" %>
              </li><span>　</span>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: "btn btn-light" %>
              </li><span>　</span>
              <li class="nav-item">
                <%= link_to "カート", cart_items_path, class: "btn btn-light" %>
              </li><span>　</span>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-light" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'About', about_path, class: "btn btn-light" %>
              </li><span>　</span>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: "btn btn-light" %>
              </li><span>　</span>
              <li class="nav-item">
                <%= link_to '新規登録', new_customer_registration_path, class: "btn btn-light" %>
              </li><span>　</span>
              <li class="nav-item">
                <%= link_to 'ログイン', new_customer_session_path, class: "btn btn-light" %>
              </li>
            <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
    </footer>

  </body>
</html>